---
name: "Tag Golang"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "golang.spec"


jobs:
  check-editorconfig:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: hack/tag.sh golang
